require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.1
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/*'
    - 'config/puma.rb'

Performance:
  Exclude:
    - '**/test/**/*'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - test/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - test/**/*

Lint/UnusedMethodArgument:
  AutoCorrect: false

Style/NegatedIf:
  Enabled: false
