services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ruby_uchi_development

  web:
    build:
      context: .
      args:
        - RAILS_ENV=development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - VITE_RUBY_HOST=vite
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - vite

  vite:
    build:
      context: .
      args:
        - RAILS_ENV=development
    command: bash -c "bin/vite dev"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - VITE_RUBY_HOST=0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3036:3036"

networks:
  default:
    name: ruby_uchi_network

volumes:
  postgres_data:
